FROM golang:1.19.4

RUN apt update -y

ENV GO111MODULE on
WORKDIR /go/src/work

RUN go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest && \
    go install github.com/ramya-rao-a/go-outline@latest && \
    go install github.com/nsf/gocode@latest && \
    go install github.com/acroca/go-symbols@latest && \
    go install github.com/fatih/gomodifytags@latest && \
    go install github.com/josharian/impl@latest && \
    go install github.com/haya14busa/goplay/cmd/goplay@latest && \
    go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install golang.org/x/lint/golint@latest && \
    go install golang.org/x/tools/gopls@latest